name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tii-deb-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros2_distro: [foxy, galactic]
    steps:
      - name: Checkout indoor_pos
        uses: actions/checkout@v2
        with:
          path: indoor_pos
      - name: Run indoor_pos docker build
        env:
          ROS: 1
          ROS_DISTRO: ${{ matrix.ros2_distro }}
          PACKAGE_NAME: indoor-pos
        run: |
          set -eux
          mkdir bin
          pushd indoor_pos
          ./build.sh ../bin/
          popd
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: indoor_pos
          path: bin/*.deb
          retention-days: 1

  artifactory:
    runs-on: ubuntu-latest
    needs: tii-deb-build
    if: github.event_name == 'push'
    steps:
      - name: Download builds
        uses: actions/download-artifact@v2
        with:
          name: indoor_pos
          path: bin
      - uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ARTIFACTORY_1: ${{ secrets.ARTIFACTORY_TOKEN }}
      - name: Upload to Artifactory
        env:
          ARTIFACTORY_REPO: debian-public-local
          DISTRIBUTION: focal
          COMPONENT: fog-sw
          ARCHITECTURE: amd64
          BUILD_NAME: indoor-pos
          CI: true
        run: |
          set -exu
          jfrog rt ping
          for pkg in bin/*.deb
          do
            pkg_name=$(basename $pkg)
            jfrog rt u --deb "$DISTRIBUTION/$COMPONENT/$ARCHITECTURE" \
                       --target-props COMMIT="$GITHUB_SHA" \
                       --build-name "$BUILD_NAME" \
                       --build-number "$GITHUB_SHA" \
                       "$pkg" \
                       "$ARTIFACTORY_REPO/$pkg_name"
          done
          jfrog rt build-publish "$BUILD_NAME" "$GITHUB_SHA"
          jfrog rt bpr "$BUILD_NAME" "$GITHUB_SHA" "$ARTIFACTORY_REPO" \
                       --status dev \
                       --comment "development build"
